# Generated by Django 4.2.5 on 2023-11-07 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lead',
            old_name='agen',
            new_name='agent',
        ),
    ]
